#Jake Eaton

import time
from typing import type     #Imports time module as well as the code objects from external scripts
from clear import clear

def Intro():         #Defines the code below as the Intro object
    type("As you start to wake up, you hear shouting and movement all around you\n")      #Uses imported type object to print the letters individually
    time.sleep(2)           #Pauses code for 2 seconds
    type("You open your eyes and see a blurry haze of lights\n")
    time.sleep(2)
    type("You feel a pain in your head as your eyes start to focus\n")
    time.sleep(2)
    type("You look around and you realise the gravity of the situation\n")
    time.sleep(2)    
    type("You sit bolt upright, noticing that you have been chained to a chair\n")
    time.sleep(2)
    type("As your senses return, your enhanced eyesight picks up details all over the room\n")
    time.sleep(2)    
    type("You spot oxygen regulators in the corners of the room which told you that you were in space... a space station of some kind? Or a ship?\n")
    time.sleep(2)
    type("You see cables hanging from the ceiling and all around you were people at computers talking and tapping away\n")
    time.sleep(2)
    type("Before you could notice anything else, someone walks in front of you\n")
    time.sleep(2)
    type("You look at the figure and notice that they are wearing a suit of armour\n")
    time.sleep(2)
    type("The black helmet covered the face of this mysterious figure\n")
    time.sleep(2)
    type("As you look down, you notice a pistol magnetically attached to their waist\n")
    time.sleep(2)
    type("'What is your name?' the woman asked\n")
    name = input(">> ")     #Used to take user input
    print("")
    type("'My name is "+name+"' you say\n")
    time.sleep(2)
    type("'I am sure you have lots of questions "+name+" so I will get right into it' the woman replies\n")
    time.sleep(2)
    type("She takes a step back. 'Welcome to the Artemis. A science research station orbiting Jupiter.'\n")
    time.sleep(2)
    type("You take another look around. The place looked like it hadn't been used for years\n")
    time.sleep(2)
    type("'Care to tell me why I am here?' you say\n")
    time.sleep(2)
    type("'You have something we want.' the woman replied\n")
    time.sleep(2)
    type("You look directly into her visor. Her voice is familiar...\n")
    time.sleep(2)
    type("'You're not an ordinary human are you?' she asked\n")
    time.sleep(2)
    type("She was right. But how did she know? You were part of a highly classified experience which turned you into a very different person...\n")
    time.sleep(2)
    type("You became stronger, faster, more agile, more alert, more intelligent. You became a super soldier. But you left that life behind years ago after losing your entire 3,000 strong squad in one battle. A battle in which only you survived...\n")
    time.sleep(2)
    type("'You're mind isn't the same as it once was is it?' she says\n")
    time.sleep(2)    
    type("You stay silent. She was right again. The PTSD had haunted you for years. You keep having visions, hallucinations. Your training had taught you that violence was always the first response...\n")
    time.sleep(2)    
    type("You have been a dangerous person for a while. So much so that you left your entire life behind to escape and try and move on from the past\n")
    time.sleep(2)    
    type("'We are here on behalf of Admiral James Osbourne. You are here to give us access to your memories so we can see what happened to you. That way, we can help you.'\n")
    time.sleep(2)    
    type("'And in return?' you ask\n")
    time.sleep(2)    
    type("'As I said, we want access to your memories. Afterwards, if you want, we will accept help in training our soldiers to fight in our war.'\n")
    time.sleep(2)    
    type("All the pieces fell into place and you had to respond\n")
    time.sleep(2)    
    type("You weren't going to help the Formula Front. You rip the chains apart and run the woman\n")
    time.sleep(2)    
    type("She reacted like lightning and shot you with something mounted on her wrist\n")
    time.sleep(2)    
    type("You fell to the floor instantly and the world went blank...\n")
    time.sleep(4)
    type("When you finally woke up, you felt yourself lying on something metal. You try to move but find yourself clamped down\n")
    time.sleep(2)        
    type("'The clamps are made with warship grade titanium alloy. So I wouldn't try to break it' called a voice\n")
    time.sleep(2)    
    type("'What do you really want? If you wanted my augmentations you would just my blood. Why am I really here?' you shout back\n")
    time.sleep(2)    
    type("The woman laughs and walks up to you\n")
    time.sleep(2)    
    type("'You've figured it out then! Yes we could take your blood and try to reverse engineer it. Or... we can use you as a test subject for this machine. I am defying orders by doing this so you better make it worth my time!' she responded\n")
    time.sleep(2)    
    type("You will not get anything from me! I'll die before I tell you anything!' you shout back\n")
    time.sleep(2)    
    type("'Don't worry! We aren't going to interrogate you. This machine will force you to give us what we want' she replied\n")
    time.sleep(2)    
    type("Suddenly, you hear something whirring behind you\n")
    time.sleep(2)    
    type("You feel a drill spin its way into the back of your neck and you begin to cry out in pain\n")
    time.sleep(2)    
    type("The drill continues to spin as you fell blood dripping out\n")
    time.sleep(2)    
    type("You feel something exit the tip of the drill and begin to move around your brain\n")
    time.sleep(2)
    type("As the drill stopped spinning, the pain subsided, but blood continued to fall\n")
    time.sleep(2)        
    type("The neural implant will give us access to your mind. You will have to repeat some of your memories in the exact same way that they happened to build up the connection while we search for what we want.' the woman said\n")
    time.sleep(2)        
    type("Repeat your memories? What does this machine do?\n")
    time.sleep(2)        
    type("'Prepare for us to enter your mind.' the woman called\n")
    time.sleep(2)        
    type("You hear screams, shouting, crying, laughing...\n")
    time.sleep(2)        
    type("You begin to see your memories all at at once\n")
    time.sleep(2)        
    type("Your neck and brain begins to burn and you cry out in pain...\n")
    time.sleep(2)        
    type("You go silent...\n")
    time.sleep(3) 
    clear()     #Clears terminal using imported clear object      