#Jake Eaton
#Introduction

import time
import sys
from os import system, name
from typing import type, type2
from clear import clear

def Intro():                            #Defines all indented code as Intro
    type("You feel yourself being dragged along the floor\n")
    time.sleep(2)
    type("You open your eyes to see a blurry haze of lights\n")
    time.sleep(2)
    type("Your head starts to ring as you hear shouting all around you\n")
    time.sleep(2)
    type("You can feel yourself get dragged onto a chair\n")
    time.sleep(2)
    type("As your senses start to return to you, the reality of your situation hits you in the face\n")
    time.sleep(2)
    type("You suddenly sit bolt upright, realising that you have been chained to the chair\n")
    time.sleep(2)
    type("You look around, your enhanced eyesight picking up details all around you\n")
    time.sleep(2)
    type("You spot oxygen regulators in the corners of the room\n")
    time.sleep(2)
    type("Realising you're in space, you start to look around to try and recognise where you are\n")
    time.sleep(2)
    type("Before you can however, a woman walks in front of you\n")
    time.sleep(2)
    type("You look up and try to make out her face but she was wearing a dark helmet\n")
    time.sleep(2)
    type("You look down at her body and realise that she was wearing a full suit of armour with a pistol attached to it\n")
    time.sleep(2)
    type("'What is your name?' asked the woman\n")
    name = input(">> ")
    print("")
    type("'My name is "+name+"' you say\n")
    time.sleep(2)
    type("'I am sure you have lots of questions "+name+" so I will get right into it.'\n")
    time.sleep(2)
    type("She steps back. 'Welcome to the Artemis. A science research station orbiting Jupiter.'\n")
    time.sleep(2)
    type("You look around. The place looked old and dirty. Like it hadn't been used for years\n")
    time.sleep(2)
    type("'Why am I here?' you ask\n")
    time.sleep(2)
    type("'You have something we want.' the woman replies\n")
    time.sleep(2)
    type("You look at her, puzzled\n")
    time.sleep(2)
    type("'You're not an ordinary human are you?' she asked\n")
    time.sleep(2)
    type("You weren't. Since you were a part of a highly classified experiment, you were a very different person\n")
    time.sleep(2)
    type("'You became stronger, faster, more agile, more alert, more intelligent. Yet you were put down as a failure.' she said\n")
    time.sleep(2)
    type("Once again, she was right. The experiment was written as a failure due to the side effects of the treatments you were given\n")
    time.sleep(2)
    type("'You've been driven insane haven't you?' she asks\n")
    time.sleep(2)
    type("Your mind is certainly not what it once was. You keep having visions, hallucinations and you always turn to violence as the first solution to any problem\n")
    time.sleep(2)
    type("'You're not a failure to us "+name+".'\n")
    time.sleep(2)
    type("'Cut the chatter. I demand to know who you are working for and why I am here!' you shout.\n")
    time.sleep(2)
    type("'We are here on behalf of Admiral James Osbourne. You are here to give us access to your memories. We want to see what happened to you so we can help you.' the woman replies\n")
    time.sleep(2)
    type("'And what do you want in return?' you ask\n")
    time.sleep(2)
    type("'Your help in training better soldiers to help us in our war.'\n")
    time.sleep(2)
    type("Suddenly all the pieces fell into place and you responded\n")
    time.sleep(2)
    type("You pull the chains apart and run at the woman\n")
    time.sleep(2)
    type("Before you could reach her, she you felt something hit your back and you fell to the ground\n")
    time.sleep(2)
    type("The world began to blur...\n")
    time.sleep(4)
    type("When you finally woke up, you felt yourself lying on something metal. You try to move but find yourself clamped down, unable to move\n")
    time.sleep(2)
    type("You try to pull yourself free\n")
    time.sleep(2)
    type("'I wouldn't do that if I were you!' called a voice. 'That is warship grade titanium alloy. You won't be able to break it.'\n")
    time.sleep(2)
    type("'You will not get anything from me! I'll die before I tell you anything! The Formula Front will lose!' you cry out\n")
    time.sleep(2)
    type("The woman laughs\n")
    time.sleep(2)
    type("'Don't worry. We aren't going to interrogate you. We have other methods.'\n")
    time.sleep(2)
    type("You suddenly hear something whirring behind you\n")
    time.sleep(2)
    type("You feel a drill spin its way into the back of your neck and you begin to cry out in pain\n")
    time.sleep(2)
    type("The drill spins inside your head and you feel the blood dripping out\n")
    time.sleep(2)
    type("Something exits the tip of the drill and begins to move around your brain\n")
    time.sleep(2)
    type("The pain subsided but the blood continued to fall\n")
    time.sleep(2)
    type("'Prepare for us to enter your mind' the woman said\n")
    time.sleep(2)
    type("You breathe heavily and close your eyes\n")
    time.sleep(2)
    type("You don't know what is about ot happen.")
    time.sleep(2)
    type("You hear screams, shouting, crying, laughing...\n")
    time.sleep(2)
    type("Your mind starts to bring back all your memories at once")
    time.sleep(2)
    type("You cry out in pain until the pain suddenly disappears...")
    time.sleep(2)
    type("You go silent...")
    time.sleep(3)
    clear()
