#Jake Eaton

def Main_Game():
    from room import Room
    from introductionv2 import Intro
    from deathv2 import Death                                                         #Imports Room, Intro, Death, Victory, type, type2 and Main_Menu Definitions
    from victoryv2 import Victory
    from typing import type, type2
    from clear import clear
    import time
    import os
    import sys
    os.environ['PYGAME_HIDE_SUPPORT_PROMPT'] = "hide"
    from pygame import mixer

    #Intro()

    first_room = Room("The old ruins of an ancient Castle\n")
    first_room.set_description("You recognise the old castle as the place you lost your friend. She fell from the tallest tower. The castle has remained closed ever since.\n")
    #This set defines each of the different rooms used in the game
    second_room = Room("A large office\n")
    second_room.set_description("You recognise this office as the office of your boss. Admiral Cora Jean of the World Space Command...\n")

    third_room = Room("A riverside resturant\n")
    third_room.set_description("One of the darkest days of your life. It was here where you were betrayed.\n")

    forth_room = Room("The Artemis\n")
    forth_room.set_description("You don't remember this... or rather... you don't want to remember this...\n")

    mixer.init()
    mixer.music.load("Battle.Of.The.Heroes.mp3")                                    #Plays mp3 file
    mixer.music.play(10)

    current_room = first_room                                                       #Sets the current room as the first room

    dead = False                                                                    #Sets dead state to be False

    while dead == False:
        type("You suddenly find yourself focusing on one memory...\n")

        time.sleep(2)

        current_room.get_details()

        time.sleep(4)

        type("You can't figure out why the people want to see this memory but you proceed\n")
        time.sleep(2)
        type("You walk forwards and reach the tall doors where a staff member stops you\n")
        time.sleep(2)
        type("'Welcome! Can I see your ticket please?' they said\n")
        time.sleep(2)
        type("You hand the staff member your ticket and you are moved over to a group\n")
        time.sleep(2)
        type("Soon after, you walk with the group through the doors and you are left alone to explore\n")
        time.sleep(2)
        type("You look around...\n")
        time.sleep(2)
        type("You spot your friend at the top of the ruins taking pictures\n")
        time.sleep(2)
        type("You smile and begin to look around. How are you going to get there?\n")
        time.sleep(2)
        type("Will you take the damaged left stairs or the right stairs?\n")
        time.sleep(2)
        type("Type Right or Left depending on which way you want to go")
        time.sleep(2)
        answer1 = input("\n")
        if answer1.lower() == "left":
            print("")
            type("The memory corrupts...\n")
            time.sleep(2)
            type("You can't see anything\n")
            time.sleep(2)
            type("Your brain and neck aches in pain...\n")
            time.sleep(2)
            clear()
            Death()
            dead = True

        elif answer1.lower() == "right":
            print("")
            type("You head right and move up the stairs\n")
            time.sleep(2)
            type("You squeeze through the crowd and make your way to your friend\n")
            time.sleep(2)
            type("As you approach, she smiles at you\n")
            time.sleep(2)
            type("You walk up to her and she shows you some of the pictures she took\n")
            time.sleep(2)
            type("You take the phone from her to get a better look\n")
            time.sleep(2)
            type("Suddenly, someone turns and pushes your friend over the wall of the tallest tower...\n")
            time.sleep(2)
            type("You try to grab her but it is too late...\n")
            time.sleep(2)
            type("She didn't even scream...\n")
            time.sleep(2)
            type("You couldn't look as she hit the sharp rocks...\n")
            time.sleep(2)
            type("You turned to face the person who did it but they had already run off\n")
            time.sleep(2)
            type("You felt lost...\n")
            time.sleep(2)
            type("You leaned against the wall and broke down into tears...\n")
            time.sleep(2)
            type("You looked over and saw her body impaled on the rocks\n")
            time.sleep(2)
            type("You begin to shake violently and fall to the floor\n")
            time.sleep(2)
            type("You hold her phone close to your heart...\n")
            clear()

        current_room = second_room

        type("You suddenly find yourself focusing on another memory...\n")
        time.sleep(2)

        current_room.get_details()
        
        print("")
        time.sleep(4)
        type("Why on earth do they want this memory?\n")
        time.sleep(2)
        type("Sitting at your boss' desk, you tapped on her desk...\n")
        time.sleep(2)
        type("It lit up and you began searching through it for the file you wanted\n")
        time.sleep(2)
        type("You eventually saw it. The file. Your file. You tap on it and it opens...\n")
        time.sleep(2)
        type("Horrified by what you read, you plugged in a USB drive and quickly move the file to it\n")
        time.sleep(2)
        type("You remove the drive and attach it to the chain on your neck\n")
        time.sleep(2)
        type("You turn the desk computer off and begin to walk to the door\n")
        time.sleep(2)
        type("Just as you are about to leave however, you hear footsteps and the Admiral's voice coming closer...\n")
        time.sleep(2)
        type("You begin to panic\n")
        time.sleep(2)
        type("Do you hide or run?\n")
        time.sleep(2)
        type("Type Hide or Run depending on what you want to do...")
        answer3 = input("\n")
        if answer3.lower() == "hide":
            type("\n")
            type("The memory corrupts...\n")
            time.sleep(2)
            type("You can't see anything\n")
            time.sleep(2)
            type("Your brain and neck aches in pain...\n")
            time.sleep(2)
            Death()
            dead = True

        elif answer3.lower() == "run":
            print("")
            type("You open the door and run...\n")
            time.sleep(2)
            type("'Stop! Someone stop him!' shouted a voice.'\n")
            mixer.music.load("Gunfire.mp3")
            mixer.music.play(1)
            type("You hear gunfire behind you...\n")
            time.sleep(2)
            type("You turn a corner and are met with a crowd of people\n")
            time.sleep(2)
            mixer.music.load("GunsReady.mp3")
            mixer.music.play(1)
            type("You are then surrounded by security guards...\n")
            time.sleep(2)
            type("You raise your hands and get down on the ground...\n")
            time.sleep(4)
            clear()

        print("")
        type("'We're almost there! The connection is stable.' you hear a voice shout\n")
        time.sleep(2)
        type("'Find that memory now!' shouted a woman\n")
        time.sleep(2)
        type("'Give him the memory of me. That will open him up.' you hear the woman say\n")
        time.sleep(2)
        type("Memory of her? You don't her... do you?\n")
        time.sleep(2)
        type("You concentrate and let the memories flow...\n")
        time.sleep(2)
        mixer.music.load("Battle.Of.The.Heroes.mp3")
        mixer.music.play(10)

        current_room = third_room
        time.sleep(2)

        clear()

        type("You prepared yourself for this memory...\n")

        current_room.get_details()
        time.sleep(4)

        type("No\n")
        time.sleep(2)
        type("It can't be...\n")
        time.sleep(2)
        type("You look at the person sitting opposite you and recognise her...\n")
        time.sleep(2)
        type("Emily. The woman who betrayed your heart...\n")
        time.sleep(2)
        type("You wanted nothing more than to lunge at her and kill her...\n")
        time.sleep(2)
        type("But you knew you had to let the memory flow\n")
        time.sleep(2)
        type("You can't change the past...\n")
        time.sleep(2)
        type("But you intend to do something about it in the present...\n")
        time.sleep(2)
        type("One of the resturant staff came up to you with their card machine to pay\n")
        time.sleep(2)
        type("You pay and the staff member goes to fetch some drinks\n")
        time.sleep(2)
        type("'On the house' he says\n")
        time.sleep(2)
        type("You thank him and turn to face Emily\n")
        time.sleep(2)
        type("You both raise your glasses and take a drink\n")
        time.sleep(2)
        type("Your throat suddenly burns and you clutch at your chest...\n")
        time.sleep(2)
        type("Emily just smiles at you...\n")
        time.sleep(2)
        type("You stand and attempt to walk out...\n")
        time.sleep(2)
        type("You collapse onto the floor...\n")
        time.sleep(2)
        mixer.music.load("GunsReady.mp3")
        mixer.music.play()
        type("You roll over onto your back and see guns pointing at you\n")
        time.sleep(2)
        type("You close your eyes and wait for your life to end...\n")
        clear()

        current_room = forth_room
        
        time.sleep(2)
        print("")
        type("'I found it!' shouted a voice\n")
        time.sleep(2)
        type("'Focus on that memory!' replied a woman\n")
        time.sleep(2)
        type("'Last memory...' you think to yourself...\n")
        time.sleep(2)
        type("You don't think you can survive much longer...\n")
        mixer.music.load("Battle.Of.The.Heroes.mp3")
        time.sleep(2)

        clear()

        current_room.get_details()

        time.sleep(4)
        type("Breathing calmly, you lean your head back. You don't want to see the needles enter your body.\n")
        time.sleep(2)
        type("Held tightly against a weird looking machine, you suddenly find yourself being rotated backwards so you are led down\n")
        time.sleep(2)
        type("'Test Subject 66 is ready for Preliminary Tests!'' you hear a voice call out\n")
        time.sleep(2)
        type("'Preparing injections.' another voice says\n")
        time.sleep(2)
        type("You hear the machine whirring...\n")
        time.sleep(2)
        type("You close your eyes and breath gently...\n")
        time.sleep(2)
        type("'Injecting Subject.' said one of the voices\n")
        time.sleep(2)
        type("You may have had injections before but these were painful\n")
        time.sleep(2)
        type("The pain only lasted a few seconds...\n")
        time.sleep(2)
        type("'Test Subject 66 has accepted primary injections. Preparing secondary.' said the first voice\n")
        time.sleep(2)
        type("'Its not over?' you think to yourself as the machine whirred again\n")
        time.sleep(2)
        type("'Injecting Subject.' said the second voice\n")
        time.sleep(2)
        type("Before you could brace youself, you suddenly felt a burning sensation over your entire body\n")
        time.sleep(2)
        type("You begin to yell out in pain\n")
        time.sleep(2)
        type("'Secondary Injections complete!' said the first voice\n")
        time.sleep(2)
        type("'Why am I still burning alive then?' you thought to yourself\n")
        time.sleep(2)
        type("It took at least 30 seconds for the burning to stop but it felt like an eternity\n")
        time.sleep(2)
        type("When it finally did stop, one of the people approached you\n")
        time.sleep(2)
        type("'Test Subject 66 has accepted Secondary Injections...\n")
        time.sleep(2)
        type("'Breathing is stable...'\n")
        time.sleep(2)
        type("'One last injection just to finish up'\n")
        time.sleep(2)
        type("You keep your eyes welded shut as you wait for the final step to complete\n")
        time.sleep(2)
        
        clear()

        type("Your eyes fly open and you scream in pain as the neural implant is removed from your neck\n")
        time.sleep(2)
        type("'Did we get everything?' said a woman's voice\n")
        time.sleep(2)
        type("'Yes!' shouted another voice\n")
        time.sleep(2)
        type("You open your eyes to see the armoured woman standing in front of you.\n")
        time.sleep(2)
        type("She removed her helmet and her dark hair was revealed\n")
        time.sleep(2)
        type("You try to lunge at the woman. 'Emily!' you shout\n")
        time.sleep(2)
        type("Emily smiled at you\n")
        time.sleep(2)
        type("'It has been a while.' she spoke calmly. 'As you know, you're augmentations were far superior to mine. Now we have the memory, we have what we need to refine your design and create soldiers like you. But better.'\n")
        time.sleep(2)
        type("'So what happens now?' you ask. 'Going to throw me in a cell somewhere?'\n")
        time.sleep(2)
        type("Emily smiled again\n")
        time.sleep(2)
        type("'No.' she whispers\n")
        time.sleep(2)
        Victory()
        dead = True

    while dead == True:
        time.sleep(3)
        mixer.music.stop()
        clear()
        type("Thank you for playing!\n")
        time.sleep(2)
        exit()